// @flow
// flow-typed signature: 33689c6465f18e59d39e5798fca43f2c
// flow-typed version: <<STUB>>/jed_v1.1.1/flow_v0.81.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'jed'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'jed' {
    declare type JedOptions = {
        domain: string,
        locale_data: {
            [string]: {
                [string]: string,
            }
        }
    };

    declare class Jed {
        constructor(options: JedOptions): Jed,

        gettext(key: string): string,
        pgettext(context: string, key: string): string,
        ngettext(singular: string, plural: string, value: number): string,
        npgettext(context: string, singular: string, plural: string, value: number): string,

        static sprintf(string, ...Array<string | number | { [string]: any }>): string,
    }

    declare export default typeof Jed
}
